2021/01/27 17:49:40 : categories_errors 8: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 1730, in after_category_import
    thumbnail_id = result['data'][0]['ID']
IndexError: list index out of range

2021/01/27 17:49:41 : categories_errors 13: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 1730, in after_category_import
    thumbnail_id = result['data'][0]['ID']
IndexError: list index out of range

2021/01/27 17:49:41 : categories_errors 14: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 1730, in after_category_import
    thumbnail_id = result['data'][0]['ID']
IndexError: list index out of range

2021/01/27 17:49:42 : categories_errors 17: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1113, in migration
    after_import = fn_after_import(id_desc, convert_data, main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/woocommerce.py", line 1730, in after_category_import
    thumbnail_id = result['data'][0]['ID']
IndexError: list index out of range

