2021/01/23 10:19:56 : customers_errors 1: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 453, in convert_customer_export
    customer_data['code'] = address_book['entry_postcode']
TypeError: list indices must be integers or slices, not str

2021/01/23 10:19:56 : customers_errors 3: Traceback (most recent call last):
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/controllers/migration.py", line 1036, in migration
    convert = fn_convert_export(main, ext)
  File "/Users/vuhung/Desktop/dev_train_03/v32/cartmigration/models/cart/custom.py", line 453, in convert_customer_export
    customer_data['code'] = address_book['entry_postcode']
TypeError: list indices must be integers or slices, not str

